; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[admin_menu][subdir] = "contrib"
projects[admin_menu_source][subdir] = "contrib"
projects[codefilter][subdir] = "contrib"
projects[ctools][subdir] = "contrib"
projects[coffee][subdir] = "contrib"
projects[context][subdir] = "contrib"
projects[date][subdir] = "contrib"
projects[devel][subdir] = "contrib"
projects[ds][subdir] = "contrib"
projects[entity][subdir] = "contrib"
projects[features][subdir] = "contrib"
projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "1.7"
projects[strongarm][subdir] = "contrib"
projects[panels][subdir] = "contrib"
projects[pathauto][subdir] = "contrib"
projects[rules][subdir] = "contrib"
projects[token][subdir] = "contrib"
projects[views][subdir] = "contrib"
projects[smtp][subdir] = "contrib"
