; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[fboauth][subdir] = "contrib"
projects[fboauth][version] = "1.6"

projects[viewreference][subdir] = "contrib"
projects[viewreference][version] = "3.4"

projects[smtp][subdir] = "contrib"
projects[smtp][version] = "1.0"

projects[i18n][subdir] = "contrib"
projects[i18n][version] = "1.10"

projects[variable][subdir] = "contrib"
projects[variable][version] = "2.3"

projects[l10n_update][subdir] = "contrib"
projects[l10n_update][version] = "1.0-beta3"

projects[entity_translation][subdir] = "contrib"
projects[entity_translation][version] = "1.0-beta3"

; Themes

projects[adaptivetheme][version] = "3.1"
